version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: ./env/dev
    
  wordpress:
    depends_on:
      - db
    build: wordpress
    restart: always
    ports:
      - "8000:80"
    env_file: ./env/dev

volumes:
  db_data: {}